name: edspert
description: Edspert Bootcamp.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.16.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  flutter_screenutil: ^5.3.1
  dropdown_button2: ^1.4.0
  firebase_auth: ^0.15.1+1
  firebase_core: ^0.4.2+2
  firebase_storage: ^3.1.6
  http: ^0.13.4
dev_dependencies:
  build_runner: ^2.1.8
  flutter_gen_runner: ^4.1.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/png/
    - assets/images/svg/
